FROM golang:alpine AS builder
RUN mkdir /build
WORKDIR /build
RUN apk update && apk add git upx

COPY go.mod go.sum ./
RUN go mod download

ADD . /build/

# RUN go install github.com/swaggo/swag/cmd/swag@latest && swag init
RUN go build
RUN upx -9 /build/run-backend

FROM alpine
# RUN adduser -S -D -H -h /app appuser
# USER appuser

RUN apk update && apk add --no-cache tzdata
ENV TZ=Asia/Shanghai

COPY --from=builder /build/run-backend /app/
# COPY --from=builder /build/.env /app/

### 由configmap取代 -- COPY --from=builder /build/settings.yml /app/

### add by Jason Start ---
RUN mkdir -p /app/configmap
COPY --from=builder /build/settings.yml /app/configmap
RUN rm -fr /app/settings.yml
RUN ln -s /app/configmap/settings.yml /app/settings.yml
### add by Jason End ---


WORKDIR /app
CMD ["./run-backend"]
